//! Product code generation.
//!
//! This module provides the `ProductGenerator` which generates an empty
//! products.rs file. All product implementations are inlined into trait
//! implementations in traits.rs (see PRD-24).
//!
//! Historical note: This module previously generated free functions for all
//! products (geometric, wedge, inner, etc.). These were removed because:
//! 1. They duplicated the trait implementations
//! 2. Traits provide a cleaner, more idiomatic API
//! 3. Inlining enables better optimization opportunities

use proc_macro2::TokenStream;
use quote::quote;

use crate::algebra::{Algebra, ProductTable};
use crate::spec::AlgebraSpec;

/// Generates the products.rs file.
///
/// Note: This generator now produces an essentially empty file.
/// All product implementations are in traits.rs.
pub struct ProductGenerator<'a> {
    /// The algebra specification.
    spec: &'a AlgebraSpec,
}

impl<'a> ProductGenerator<'a> {
    /// Creates a new product generator.
    pub fn new(spec: &'a AlgebraSpec, _algebra: &'a Algebra, _table: ProductTable) -> Self {
        Self { spec }
    }

    /// Generates the complete products.rs file.
    ///
    /// Note: As of PRD-24, all product implementations are inlined into trait
    /// implementations in traits.rs. This file is now empty except for the header.
    pub fn generate_products_file(&self) -> TokenStream {
        let header = self.generate_header();

        quote! {
            #header

            // ============================================================
            // All product implementations are in traits.rs
            // ============================================================
            //
            // Products are implemented as trait methods:
            // - Wedge::wedge()         - exterior/wedge product
            // - Antiwedge::antiwedge() - regressive/meet product
            // - Inner::inner()         - symmetric inner product
            // - LeftContract::left_contract()   - left contraction
            // - RightContract::right_contract() - right contraction
            // - Dot::dot()             - metric dot product
            // - Antidot::antidot()     - metric antidot product
            // - ScalarProduct::scalar_product() - grade-0 projection
            // - BulkContract::bulk_contract()   - a ∨ b★
            // - WeightContract::weight_contract() - a ∨ b☆
            // - BulkExpand::bulk_expand()       - a ∧ b★
            // - WeightExpand::weight_expand()   - a ∧ b☆
            // - Sandwich::sandwich()   - v × x × rev(v)
            // - Antisandwich::antisandwich() - v ⊛ x ⊛ antirev(v)
            // - Reverse::reverse()     - grade reversal
            // - Antireverse::antireverse() - antigrade reversal
            // - RightComplement::right_complement() - Hodge dual
        }
    }

    /// Generates the file header.
    fn generate_header(&self) -> TokenStream {
        let name = &self.spec.name;

        let header_doc = format!(
            r#"//! Products module for the {} algebra.
//!
//! All product implementations are in the traits module.
//! See `traits.rs` for the trait implementations.
//!
//! This file is auto-generated by clifford-codegen. Do not edit manually."#,
            name
        );

        header_doc.parse().unwrap_or_else(|_| quote! {})
    }
}
