//! Type struct generation.
//!
//! This module provides the `TypeGenerator` for generating Rust struct
//! definitions from algebra specifications.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::algebra::{Algebra, Blade};
use crate::spec::{AlgebraSpec, TypeSpec};
use crate::symbolic::{ConstraintDeriver, ConstraintSolver, SolutionType};

/// Generates Rust struct definitions for algebra types.
///
/// The generator produces complete struct definitions including:
/// - Documentation with basis ordering tables
/// - Derive macros (Clone, Copy, Debug, PartialEq, serde)
/// - Private fields with public accessors
/// - Constructors (`new`, `zero`, unit basis)
/// - Basic methods (`norm_squared`, `norm`, `reverse`)
/// - Default implementation
///
/// # Example
///
/// ```
/// use clifford_codegen::algebra::Algebra;
/// use clifford_codegen::codegen::TypeGenerator;
/// use clifford_codegen::spec::parse_spec;
///
/// let spec = parse_spec(r#"
/// [algebra]
/// name = "euclidean2"
///
/// [signature]
/// positive = ["e1", "e2"]
///
/// [types.Vector]
/// grades = [1]
/// fields = ["x", "y"]
/// "#).unwrap();
///
/// let algebra = Algebra::euclidean(2);
/// let generator = TypeGenerator::new(&spec, &algebra);
///
/// let tokens = generator.generate_types_file();
/// let code = tokens.to_string();
///
/// assert!(code.contains("pub struct Vector"));
/// assert!(code.contains("pub fn new"));
/// assert!(code.contains("pub fn x"));
/// ```
pub struct TypeGenerator<'a> {
    /// The algebra specification.
    spec: &'a AlgebraSpec,
    /// The algebra for blade computations.
    algebra: &'a Algebra,
}

impl<'a> TypeGenerator<'a> {
    /// Creates a new type generator.
    pub fn new(spec: &'a AlgebraSpec, algebra: &'a Algebra) -> Self {
        Self { spec, algebra }
    }

    /// Generates the complete types.rs file.
    pub fn generate_types_file(&self) -> TokenStream {
        let header = self.generate_header();
        let imports = self.generate_imports();
        let types: Vec<TokenStream> = self
            .spec
            .types
            .iter()
            .filter(|ty| ty.alias_of.is_none()) // Skip aliases
            .map(|ty| self.generate_type(ty))
            .collect();

        let aliases: Vec<TokenStream> = self
            .spec
            .types
            .iter()
            .filter(|ty| ty.alias_of.is_some())
            .map(|ty| self.generate_alias(ty))
            .collect();

        let wrapper_aliases = self.generate_wrapper_aliases();

        quote! {
            #header
            #imports

            #(#types)*

            #(#aliases)*

            #wrapper_aliases
        }
    }

    /// Generates the file header comment.
    fn generate_header(&self) -> TokenStream {
        let name = &self.spec.name;
        let description = self
            .spec
            .description
            .as_deref()
            .unwrap_or("Generated algebra types");

        let header_doc = format!(
            r#"//! Type definitions for {}.
//!
//! {}
//!
//! This file is auto-generated by clifford-codegen.
//! Do not edit manually.

// Allow clippy lints that are unavoidable in generated code
#![allow(clippy::too_many_arguments)]"#,
            name, description
        );

        // Use a raw token to preserve the comment format
        header_doc.parse().unwrap_or_else(|_| quote! {})
    }

    /// Generates import statements.
    fn generate_imports(&self) -> TokenStream {
        quote! {
            use crate::scalar::Float;

            #[cfg(feature = "serde")]
            use serde::{Serialize, Deserialize};
        }
    }

    /// Generates a type alias.
    fn generate_alias(&self, ty: &TypeSpec) -> TokenStream {
        let name = format_ident!("{}", ty.name);
        let target_name = ty.alias_of.as_ref().unwrap();
        let target = format_ident!("{}", target_name);
        let description = ty
            .description
            .clone()
            .unwrap_or_else(|| format!("Alias for {}.", target_name));

        quote! {
            #[doc = #description]
            pub type #name<T> = #target<T>;
        }
    }

    /// Generates a single type definition.
    pub fn generate_type(&self, ty: &TypeSpec) -> TokenStream {
        let name = format_ident!("{}", ty.name);
        let doc = self.generate_type_doc(ty);
        let derives = self.generate_derives();
        let fields = self.generate_fields(ty);
        let impl_block = self.generate_impl(ty);
        let default_impl = self.generate_default(ty);

        quote! {
            #doc
            #derives
            #[repr(C)]
            pub struct #name<T: Float> {
                #fields
            }

            #impl_block
            #default_impl
        }
    }

    /// Generates documentation for a type.
    fn generate_type_doc(&self, ty: &TypeSpec) -> TokenStream {
        let description = ty.description.as_deref().unwrap_or(&ty.name);
        let basis_table = self.generate_basis_table(ty);
        let example = self.generate_example(ty);

        let doc_string = format!(
            "{}\n\n# Basis Ordering\n\n{}\n\n# Example\n\n```\n{}\n```",
            description, basis_table, example
        );

        quote! {
            #[doc = #doc_string]
        }
    }

    /// Generates a markdown table of basis elements.
    fn generate_basis_table(&self, ty: &TypeSpec) -> String {
        let mut table = String::from("| Index | Blade | Field |\n|-------|-------|-------|\n");

        for field in &ty.fields {
            let blade = Blade::from_index(field.blade_index);
            let blade_name = self.algebra.blade_name(blade);
            table.push_str(&format!(
                "| {} | {} | `{}` |\n",
                field.blade_index, blade_name, field.name
            ));
        }

        table
    }

    /// Generates an example usage.
    fn generate_example(&self, ty: &TypeSpec) -> String {
        let args: Vec<String> = ty
            .fields
            .iter()
            .enumerate()
            .map(|(i, _)| format!("{}.0", i + 1))
            .collect();

        let module_path = self.spec.module_path.as_deref().unwrap_or("generated");

        format!(
            "use clifford::specialized::{}::{};\n\nlet v = {}::new_unchecked({});",
            module_path,
            ty.name,
            ty.name,
            args.join(", ")
        )
    }

    /// Generates derive macros.
    fn generate_derives(&self) -> TokenStream {
        quote! {
            #[derive(Clone, Copy, Debug, PartialEq)]
            #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
        }
    }

    /// Generates struct fields.
    fn generate_fields(&self, ty: &TypeSpec) -> TokenStream {
        let fields: Vec<TokenStream> = ty
            .fields
            .iter()
            .map(|field| {
                let name = format_ident!("{}", field.name);
                // Use the field name from the TOML spec, not the computed blade name
                let doc = format!("Coefficient of `{}`.", field.name);

                quote! {
                    #[doc = #doc]
                    #name: T,
                }
            })
            .collect();

        quote! { #(#fields)* }
    }

    /// Generates the impl block with all methods.
    fn generate_impl(&self, ty: &TypeSpec) -> TokenStream {
        let name = format_ident!("{}", ty.name);
        let constructor = self.generate_constructor(ty);
        let constraint_constructors = self.generate_constraint_constructors(ty);
        let accessors = self.generate_accessors(ty);
        let zero = self.generate_zero(ty);
        let unit_elements = self.generate_unit_elements(ty);
        let norm_methods = self.generate_norm_methods(ty);
        let reverse = self.generate_reverse(ty);
        let antireverse = self.generate_antireverse(ty);

        quote! {
            impl<T: Float> #name<T> {
                #constructor
                #constraint_constructors
                #accessors
                #zero
                #unit_elements
                #norm_methods
                #reverse
                #antireverse
            }
        }
    }

    /// Generates constructors.
    ///
    /// For types WITHOUT constraints:
    /// - `new()` - the primary constructor
    /// - `new_unchecked()` - alias for `new()`
    ///
    /// For types WITH constraints:
    /// - `new_unchecked()` only - no `new()` to prevent accidental invalid construction
    fn generate_constructor(&self, ty: &TypeSpec) -> TokenStream {
        let params: Vec<TokenStream> = ty
            .fields
            .iter()
            .map(|field| {
                let name = format_ident!("{}", field.name);
                quote! { #name: T }
            })
            .collect();

        let field_inits: Vec<TokenStream> = ty
            .fields
            .iter()
            .map(|field| {
                let name = format_ident!("{}", field.name);
                quote! { #name }
            })
            .collect();

        // Check if this type has a constraint
        let has_constraint = self.type_has_constraint(ty);

        if has_constraint {
            // Constrained types: only new_unchecked(), no new()
            quote! {
                /// Creates a new element from components without validation.
                ///
                /// **Warning:** This does not validate the geometric constraint.
                /// Use `new_checked()` to validate, or `from_components()` to
                /// construct from independent parameters.
                #[inline]
                pub fn new_unchecked(#(#params),*) -> Self {
                    Self { #(#field_inits),* }
                }
            }
        } else {
            // Unconstrained types: both new() and new_unchecked()
            let params2 = params.clone();
            quote! {
                /// Creates a new element from components.
                #[inline]
                pub fn new(#(#params),*) -> Self {
                    Self { #(#field_inits),* }
                }

                /// Creates a new element from components without validation.
                ///
                /// This is an alias for `new()`. It exists for consistency with types
                /// that have geometric constraints, where unchecked construction is
                /// used in performance-critical code or trusted contexts.
                #[inline]
                pub fn new_unchecked(#(#params2),*) -> Self {
                    Self::new(#(#field_inits),*)
                }
            }
        }
    }

    /// Checks if a type has a geometric constraint.
    fn type_has_constraint(&self, ty: &TypeSpec) -> bool {
        let deriver = ConstraintDeriver::new(self.algebra, self.spec.norm.primary_involution);
        if let Some(constraint) = deriver.derive_geometric_constraint(ty, "x") {
            // Only consider single-constraint linear cases (which we can solve)
            if constraint.zero_expressions.len() == 1 {
                let expr = &constraint.zero_expressions[0];
                let expr_str = format!("{} = 0", expr);
                let solve_for_field = ty.fields.iter().max_by_key(|f| f.grade);
                if let Some(field) = solve_for_field {
                    let solver = ConstraintSolver::new();
                    let symbol_name = format!("x_{}", field.name);
                    if let Ok(solution) = solver.solve(&expr_str, &symbol_name) {
                        return solution.solution_type == SolutionType::Linear;
                    }
                }
            }
        }
        false
    }

    /// Generates constraint-checking constructors for types with geometric constraints.
    ///
    /// For types with derived constraints (e.g., Motor with Study condition), generates:
    /// - `new_checked()` - validates the constraint and returns `Result<Self, ConstraintError>`
    /// - `from_components()` - takes N-1 free parameters and computes the constrained field
    ///
    /// Returns empty TokenStream for types without constraints.
    fn generate_constraint_constructors(&self, ty: &TypeSpec) -> TokenStream {
        // Derive constraint from algebra structure
        let deriver = ConstraintDeriver::new(self.algebra, self.spec.norm.primary_involution);
        let constraint = match deriver.derive_geometric_constraint(ty, "self") {
            Some(c) => c,
            None => return quote! {}, // No constraint for this type
        };

        // Only handle single-constraint cases
        if constraint.zero_expressions.len() != 1 {
            return quote! {};
        }

        let expr = &constraint.zero_expressions[0];
        let expr_str = format!("{} = 0", expr);

        // Find the highest-grade field to solve for (typically pseudoscalar like e0123)
        let solve_for_field = match ty.fields.iter().max_by_key(|f| f.grade) {
            Some(f) => f,
            None => return quote! {},
        };

        // Try to solve the constraint
        let solver = ConstraintSolver::new();
        let symbol_name = format!("self_{}", solve_for_field.name);
        let solution = match solver.solve(&expr_str, &symbol_name) {
            Ok(s) => s,
            Err(_) => return quote! {},
        };

        // Skip quadratic constraints for now (they require sqrt)
        if solution.solution_type == SolutionType::Quadratic {
            return quote! {};
        }

        let new_checked = self.generate_new_checked(ty, &solution);
        let from_components = self.generate_from_components(ty, &solution);

        quote! {
            #new_checked
            #from_components
        }
    }

    /// Generates the `new_checked()` constructor that validates the constraint.
    fn generate_new_checked(
        &self,
        ty: &TypeSpec,
        solution: &crate::symbolic::SolveResult,
    ) -> TokenStream {
        // Get all field params
        let params: Vec<TokenStream> = ty
            .fields
            .iter()
            .map(|field| {
                let name = format_ident!("{}", field.name);
                quote! { #name: T }
            })
            .collect();

        let field_inits: Vec<TokenStream> = ty
            .fields
            .iter()
            .map(|field| {
                let name = format_ident!("{}", field.name);
                quote! { #name }
            })
            .collect();

        // Build the expected value expression from the solution
        let solve_for_field = ty.fields.iter().max_by_key(|f| f.grade).unwrap();
        let solve_for_name = format_ident!("{}", solve_for_field.name);

        let numerator_expr = self.convert_constraint_solution_to_tokens(&solution.numerator, ty);
        let expected_expr = if let Some(ref divisor) = solution.divisor {
            let divisor_expr = self.convert_constraint_solution_to_tokens(divisor, ty);
            quote! { (#numerator_expr) / (#divisor_expr) }
        } else {
            numerator_expr
        };

        let constraint_name = format!("{} constraint", ty.name);

        quote! {
            /// Creates a new element, validating the geometric constraint.
            ///
            /// Returns `Err` if the constraint is violated beyond the given tolerance.
            #[inline]
            pub fn new_checked(#(#params),*, tolerance: T) -> Result<Self, &'static str> {
                let expected = #expected_expr;
                let actual = #solve_for_name;
                if (actual - expected).abs() > tolerance {
                    return Err(#constraint_name);
                }
                Ok(Self::new_unchecked(#(#field_inits),*))
            }
        }
    }

    /// Generates the `from_components()` constructor that computes the constrained field.
    fn generate_from_components(
        &self,
        ty: &TypeSpec,
        solution: &crate::symbolic::SolveResult,
    ) -> TokenStream {
        // Find the solve_for field
        let solve_for_field = ty.fields.iter().max_by_key(|f| f.grade).unwrap();

        // Generate params for free fields (all except solve_for)
        let free_params: Vec<TokenStream> = ty
            .fields
            .iter()
            .filter(|f| f.name != solve_for_field.name)
            .map(|field| {
                let name = format_ident!("{}", field.name);
                quote! { #name: T }
            })
            .collect();

        // Build the computed value expression
        let numerator_expr = self.convert_constraint_solution_to_tokens(&solution.numerator, ty);
        let computed_expr = if let Some(ref divisor) = solution.divisor {
            let divisor_expr = self.convert_constraint_solution_to_tokens(divisor, ty);
            quote! { (#numerator_expr) / (#divisor_expr) }
        } else {
            numerator_expr
        };

        // Build field initializers
        let field_inits: Vec<TokenStream> = ty
            .fields
            .iter()
            .map(|field| {
                let field_name = format_ident!("{}", field.name);
                if field.name == solve_for_field.name {
                    computed_expr.clone()
                } else {
                    quote! { #field_name }
                }
            })
            .collect();

        // Check if there's a divisor that could be zero
        let doc = format!(
            "Creates a {} from {} independent components, computing `{}`.\n\n\
             Returns `None` if the divisor would be zero (unstable computation).",
            ty.name,
            free_params.len(),
            solve_for_field.name
        );

        if let Some(ref divisor) = solution.divisor {
            let divisor_check = self.convert_constraint_solution_to_tokens(divisor, ty);
            quote! {
                #[doc = #doc]
                #[inline]
                pub fn from_components(#(#free_params),*) -> Option<Self> {
                    if (#divisor_check).abs() < T::epsilon() {
                        return None;
                    }
                    Some(Self::new_unchecked(#(#field_inits),*))
                }
            }
        } else {
            let doc_no_div = format!(
                "Creates a {} from {} independent components, computing `{}`.",
                ty.name,
                free_params.len(),
                solve_for_field.name
            );
            quote! {
                #[doc = #doc_no_div]
                #[inline]
                pub fn from_components(#(#free_params),*) -> Self {
                    Self::new_unchecked(#(#field_inits),*)
                }
            }
        }
    }

    /// Converts a solution expression string to TokenStream.
    ///
    /// Replaces "self_fieldname" patterns with actual field references.
    fn convert_constraint_solution_to_tokens(&self, expr: &str, ty: &TypeSpec) -> TokenStream {
        let mut result = expr.to_string();

        // Replace "self_fieldname" with just "fieldname"
        // Do longer names first to avoid partial replacements
        let mut sorted_fields: Vec<_> = ty.fields.iter().collect();
        sorted_fields.sort_by(|a, b| b.name.len().cmp(&a.name.len()));

        for field in sorted_fields {
            let self_pattern = format!("self_{}", field.name);
            result = result.replace(&self_pattern, &field.name);
        }

        // Parse and convert to TokenStream
        result.parse().unwrap_or_else(|_| quote! { T::zero() })
    }

    /// Generates accessor methods for each field.
    fn generate_accessors(&self, ty: &TypeSpec) -> TokenStream {
        let accessors: Vec<TokenStream> = ty
            .fields
            .iter()
            .map(|field| {
                let name = format_ident!("{}", field.name);
                // Use the field name from the TOML spec, not the computed blade name
                let doc = format!("Returns the `{}` coefficient.", field.name);

                quote! {
                    #[doc = #doc]
                    #[inline]
                    pub fn #name(&self) -> T {
                        self.#name
                    }
                }
            })
            .collect();

        quote! { #(#accessors)* }
    }

    /// Generates the zero() method for a type.
    fn generate_zero(&self, ty: &TypeSpec) -> TokenStream {
        let zeros: Vec<TokenStream> = ty.fields.iter().map(|_| quote! { T::zero() }).collect();
        let constructor = quote! { new_unchecked };

        quote! {
            /// Creates the zero element.
            #[inline]
            pub fn zero() -> Self {
                Self::#constructor(#(#zeros),*)
            }
        }
    }

    /// Generates unit basis element constructors for single-grade types.
    fn generate_unit_elements(&self, ty: &TypeSpec) -> TokenStream {
        // Only for single-grade types
        if ty.grades.len() != 1 {
            return quote! {};
        }

        let constructor = quote! { new_unchecked };

        let units: Vec<TokenStream> = ty
            .fields
            .iter()
            .enumerate()
            .map(|(i, field)| {
                let method_name = format_ident!("unit_{}", field.name);
                let blade = Blade::from_index(field.blade_index);
                let blade_name = self.algebra.blade_name(blade);
                let doc = format!("Creates the unit {} element.", blade_name);

                let values: Vec<TokenStream> = ty
                    .fields
                    .iter()
                    .enumerate()
                    .map(|(j, _)| {
                        if i == j {
                            quote! { T::one() }
                        } else {
                            quote! { T::zero() }
                        }
                    })
                    .collect();

                quote! {
                    #[doc = #doc]
                    #[inline]
                    pub fn #method_name() -> Self {
                        Self::#constructor(#(#values),*)
                    }
                }
            })
            .collect();

        quote! { #(#units)* }
    }

    /// Generates norm_squared, norm, try_normalize, normalize, and scale methods.
    fn generate_norm_methods(&self, ty: &TypeSpec) -> TokenStream {
        let field_names: Vec<_> = ty
            .fields
            .iter()
            .map(|f| format_ident!("{}", f.name))
            .collect();

        let constructor = quote! { new_unchecked };

        // Compute norm squared based on metric signature.
        // For each blade, we need to consider the metric.
        // For now, this uses Euclidean norm (sum of squares).
        // TODO: Handle non-Euclidean metrics properly (e.g., for CGA, PGA).
        let squared_terms: Vec<TokenStream> = ty
            .fields
            .iter()
            .map(|field| {
                let name = format_ident!("{}", field.name);
                let blade = Blade::from_index(field.blade_index);
                let metric = self.blade_metric(blade);

                if metric >= 0 {
                    quote! { self.#name * self.#name }
                } else {
                    // Negative metric: subtract instead of add
                    // Note: we still compute the absolute value for norm purposes
                    quote! { self.#name * self.#name }
                }
            })
            .collect();

        quote! {
            /// Returns the squared Euclidean norm.
            ///
            /// This is the sum of squares of all components.
            #[inline]
            pub fn norm_squared(&self) -> T {
                #(#squared_terms)+*
            }

            /// Returns the Euclidean norm.
            #[inline]
            pub fn norm(&self) -> T {
                self.norm_squared().sqrt()
            }

            /// Attempts to normalize this element.
            ///
            /// Returns `None` if the norm is too small (less than epsilon).
            #[inline]
            pub fn try_normalize(&self) -> Option<Self> {
                let n = self.norm();
                if n < T::epsilon() {
                    None
                } else {
                    Some(self.scale(T::one() / n))
                }
            }

            /// Normalizes this element, panicking if the norm is too small.
            ///
            /// # Panics
            ///
            /// Panics if the norm is less than epsilon.
            #[inline]
            pub fn normalize(&self) -> Self {
                self.try_normalize().expect("cannot normalize zero element")
            }

            /// Scales all components by a scalar.
            #[inline]
            pub fn scale(&self, s: T) -> Self {
                Self::#constructor(#(self.#field_names * s),*)
            }
        }
    }

    /// Computes the metric sign for a blade.
    ///
    /// Returns 1 for positive metric, -1 for negative, 0 for null.
    fn blade_metric(&self, blade: Blade) -> i32 {
        // For a blade that is a product of basis vectors,
        // the metric is the product of individual metrics.
        let mut metric = 1i32;

        for i in 0..self.algebra.dim() {
            if blade.contains(i) {
                metric *= i32::from(self.algebra.metric(i));
            }
        }

        metric
    }

    /// Generates the reverse() method.
    ///
    /// Reverse: (-1)^(k(k-1)/2) for grade k.
    pub fn generate_reverse(&self, ty: &TypeSpec) -> TokenStream {
        let reversed_values: Vec<TokenStream> = ty
            .fields
            .iter()
            .map(|field| {
                let name = format_ident!("{}", field.name);
                let grade = field.grade;
                // Sign is (-1)^(k(k-1)/2)
                let exponent = grade * grade.saturating_sub(1) / 2;
                if exponent.is_multiple_of(2) {
                    quote! { self.#name }
                } else {
                    quote! { -self.#name }
                }
            })
            .collect();

        let constructor = quote! { new_unchecked };

        quote! {
            /// Returns the reverse (reversion).
            ///
            /// For a k-blade, the reverse has sign (-1)^(k(k-1)/2):
            /// - Grade 0: +1
            /// - Grade 1: +1
            /// - Grade 2: -1
            /// - Grade 3: -1
            /// - Grade 4: +1
            /// - ...
            #[inline]
            pub fn reverse(&self) -> Self {
                Self::#constructor(#(#reversed_values),*)
            }
        }
    }

    /// Generates the antireverse() method.
    ///
    /// Antireverse: (-1)^((n-k)(n-k-1)/2) for grade k in dimension n.
    /// This is the reverse of the complement, or complement of the reverse.
    pub fn generate_antireverse(&self, ty: &TypeSpec) -> TokenStream {
        let dim = self.spec.signature.dim();

        let antireversed_values: Vec<TokenStream> = ty
            .fields
            .iter()
            .map(|field| {
                let name = format_ident!("{}", field.name);
                let grade = field.grade;
                let antigrade = dim - grade;
                // Sign is (-1)^((n-k)(n-k-1)/2)
                let exponent = antigrade * antigrade.saturating_sub(1) / 2;
                if exponent.is_multiple_of(2) {
                    quote! { self.#name }
                } else {
                    quote! { -self.#name }
                }
            })
            .collect();

        let constructor = quote! { new_unchecked };

        quote! {
            /// Returns the antireverse.
            ///
            /// For a k-blade in an n-dimensional algebra, the antireverse has sign (-1)^((n-k)(n-k-1)/2).
            /// This is equivalent to complement(reverse(complement(x))).
            ///
            /// In PGA (n=4):
            /// - Grade 0 (antigrade 4): (-1)^(4*3/2) = (-1)^6 = +1
            /// - Grade 1 (antigrade 3): (-1)^(3*2/2) = (-1)^3 = -1
            /// - Grade 2 (antigrade 2): (-1)^(2*1/2) = (-1)^1 = -1
            /// - Grade 3 (antigrade 1): (-1)^(1*0/2) = (-1)^0 = +1
            /// - Grade 4 (antigrade 0): (-1)^(0*0/2) = (-1)^0 = +1
            #[inline]
            pub fn antireverse(&self) -> Self {
                Self::#constructor(#(#antireversed_values),*)
            }
        }
    }

    /// Generates the Default implementation.
    fn generate_default(&self, ty: &TypeSpec) -> TokenStream {
        let name = format_ident!("{}", ty.name);

        // Default is always zero - identity() is context-dependent and not generated
        quote! {
            impl<T: Float> Default for #name<T> {
                fn default() -> Self {
                    Self::zero()
                }
            }
        }
    }

    /// Generates wrapper type aliases for all entity types.
    ///
    /// For every entity type (except Scalar and type aliases), generates:
    /// - `Bulk<Type>` alias: `BulkVector<T> = Bulk<Vector<T>>`
    /// - `Unitized<Type>` alias: `UnitizedVector<T> = Unitized<Vector<T>>`
    ///
    /// Additionally for Euclidean algebras, generates `Unit<T>` aliases:
    /// - `UnitVector<T> = Unit<Vector<T>>`
    fn generate_wrapper_aliases(&self) -> TokenStream {
        let mut aliases = Vec::new();
        let is_pga = self.spec.signature.r > 0;

        for ty in &self.spec.types {
            // Skip type aliases
            if ty.alias_of.is_some() {
                continue;
            }

            // Skip Scalar type - no need for Bulk/Unitized wrappers
            if ty.name == "Scalar" {
                continue;
            }

            let type_name = format_ident!("{}", ty.name);

            // Generate Bulk<T> alias for all entity types
            let bulk_alias = format_ident!("Bulk{}", ty.name);
            let bulk_doc = format!(
                "A bulk-normalized {} (bulk norm = 1).\n\n\
                 This type alias wraps {} in `Bulk<T>`, which normalizes by the bulk \
                 (non-degenerate) part of the norm.",
                ty.name, ty.name
            );

            aliases.push(quote! {
                #[doc = #bulk_doc]
                pub type #bulk_alias<T> = crate::wrappers::Bulk<#type_name<T>>;
            });

            // Generate Unitized<T> alias for all entity types
            let unitized_alias = format_ident!("Unitized{}", ty.name);
            let unitized_doc = format!(
                "A unitized {} (weight norm = 1).\n\n\
                 This type alias wraps {} in `Unitized<T>`, which normalizes by the weight \
                 (degenerate) part of the norm.",
                ty.name, ty.name
            );

            aliases.push(quote! {
                #[doc = #unitized_doc]
                pub type #unitized_alias<T> = crate::wrappers::Unitized<#type_name<T>>;
            });

            // For Euclidean algebras, also generate Unit<T> aliases for appropriate types
            if !is_pga {
                // Generate Unit aliases for types that make sense to normalize:
                // - Single-grade types (Vector, Bivector, Trivector)
                // - Rotor types (grades [0, 2])
                let should_generate_unit = ty.grades.len() == 1
                    || (ty.grades.contains(&0) && ty.grades.contains(&2) && ty.grades.len() == 2);

                if should_generate_unit {
                    let unit_alias = format_ident!("Unit{}", ty.name);
                    let unit_doc = format!(
                        "A unit {} (Euclidean norm = 1).\n\n\
                         This type alias provides compile-time documentation that the \
                         {} has been normalized.",
                        ty.name, ty.name
                    );

                    aliases.push(quote! {
                        #[doc = #unit_doc]
                        pub type #unit_alias<T> = crate::wrappers::Unit<#type_name<T>>;
                    });
                }
            }
        }

        if aliases.is_empty() {
            quote! {}
        } else {
            quote! {
                // ============================================================================
                // Wrapper Type Aliases
                // ============================================================================

                #(#aliases)*
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::parse_spec;

    #[test]
    fn generates_vector_type() {
        let spec = parse_spec(include_str!("../../../../algebras/euclidean3.toml")).unwrap();
        let algebra = Algebra::euclidean(3);
        let generator = TypeGenerator::new(&spec, &algebra);

        let tokens = generator.generate_types_file();
        let code = tokens.to_string();

        assert!(code.contains("pub struct Vector"));
        assert!(code.contains("x : T"));
        assert!(code.contains("y : T"));
        assert!(code.contains("z : T"));
        assert!(code.contains("pub fn new"));
        assert!(code.contains("pub fn x"));
    }

    #[test]
    fn field_order_is_canonical() {
        // Verify fields are ordered by grade, then by blade index
        let spec = parse_spec(include_str!("../../../../algebras/euclidean3.toml")).unwrap();
        let rotor_type = spec.types.iter().find(|t| t.name == "Rotor").unwrap();

        let field_order: Vec<&str> = rotor_type.fields.iter().map(|f| f.name.as_str()).collect();

        // Expected: s (grade 0), xy, xz, yz (grade 2)
        assert_eq!(field_order, vec!["s", "xy", "xz", "yz"]);
    }

    #[test]
    fn reverse_signs_correct() {
        // Grade 0: sign = +1
        // Grade 1: sign = +1 (0*-1/2 = 0, even)
        // Grade 2: sign = -1 (2*1/2 = 1, odd)
        // Grade 3: sign = -1 (3*2/2 = 3, odd)

        let spec = parse_spec(include_str!("../../../../algebras/euclidean3.toml")).unwrap();
        let algebra = Algebra::euclidean(3);
        let generator = TypeGenerator::new(&spec, &algebra);

        // Check Bivector reverse
        let bivector = spec.types.iter().find(|t| t.name == "Bivector").unwrap();
        let tokens = generator.generate_reverse(bivector);
        let code = tokens.to_string();

        // All bivector components should be negated
        assert!(code.contains("- self . xy"));
        assert!(code.contains("- self . xz"));
        assert!(code.contains("- self . yz"));
    }

    #[test]
    fn generates_unit_elements_for_vector() {
        let spec = parse_spec(include_str!("../../../../algebras/euclidean3.toml")).unwrap();
        let algebra = Algebra::euclidean(3);
        let generator = TypeGenerator::new(&spec, &algebra);

        let vector = spec.types.iter().find(|t| t.name == "Vector").unwrap();
        let tokens = generator.generate_unit_elements(vector);
        let code = tokens.to_string();

        // Vector should have unit_x, unit_y, unit_z
        assert!(code.contains("unit_x"));
        assert!(code.contains("unit_y"));
        assert!(code.contains("unit_z"));
    }

    #[test]
    fn no_unit_elements_for_rotor() {
        let spec = parse_spec(include_str!("../../../../algebras/euclidean3.toml")).unwrap();
        let algebra = Algebra::euclidean(3);
        let generator = TypeGenerator::new(&spec, &algebra);

        let rotor = spec.types.iter().find(|t| t.name == "Rotor").unwrap();
        let tokens = generator.generate_unit_elements(rotor);
        let code = tokens.to_string();

        // Rotor has multiple grades, so no unit elements
        assert!(code.is_empty());
    }

    #[test]
    fn generates_alias_if_present() {
        // Currently no algebras define type aliases, so this test just verifies
        // the code generation completes without errors. Type alias generation
        // would be tested when an algebra with alias_of is added.
        let spec = parse_spec(include_str!("../../../../algebras/euclidean3.toml")).unwrap();
        let algebra = Algebra::euclidean(3);
        let generator = TypeGenerator::new(&spec, &algebra);

        let tokens = generator.generate_types_file();
        let code = tokens.to_string();

        // Verify basic types are generated (aliases would appear similarly)
        assert!(code.contains("pub struct Rotor"));
    }

    #[test]
    fn generates_default_impl() {
        let spec = parse_spec(include_str!("../../../../algebras/euclidean3.toml")).unwrap();
        let algebra = Algebra::euclidean(3);
        let generator = TypeGenerator::new(&spec, &algebra);

        let rotor = spec.types.iter().find(|t| t.name == "Rotor").unwrap();
        let tokens = generator.generate_default(rotor);
        let code = tokens.to_string();

        // Default is always zero - identity is context-dependent
        assert!(code.contains("impl < T : Float > Default for Rotor"));
        assert!(code.contains("Self :: zero ()"));

        let vector = spec.types.iter().find(|t| t.name == "Vector").unwrap();
        let tokens = generator.generate_default(vector);
        let code = tokens.to_string();

        // Vector default should be zero
        assert!(code.contains("impl < T : Float > Default for Vector"));
        assert!(code.contains("Self :: zero ()"));
    }
}
